name: VehiclesPlusConverter
version: '${project.version}'
main: tech.sbdevelopment.vehiclesplusconverter.VehiclesPlusConverter
api-version: 1.19
authors: [ SBDeveloper ]
description: Conversion plugin for v2 to v3.
website: sbdevelopment.tech
softdepend:  [ VehiclesPlusPro, VehiclesPlus ]
commands:
  vpconvert:
    description: Convert the v2 to v3 data.
    permission: vpconvert.convert
permissions:
  vpconvert.convert:
    description: Use the /vpconvert command
    default: op