name: Java CI

on: [ push, workflow_dispatch ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - run: mkdir -p target

      - uses: actions/upload-artifact@master
        with:
          name: VehiclesPlus
          path: target